[package]
name = "win-containers-registry"
version = "0.1.0"
authors = ["amigin <amigin@gmail.com>"]
edition = "2024"

[dependencies]
my-http-server = { tag = "0.9.0", git = "https://github.com/MyJetTools/my-http-server.git", features = [
    "macros",
    "controllers",
] }

my-http-utils = { tag = "0.1.0", git = "https://github.com/MyJetTools/my-http-utils.git", features = [
    "server",
] }

my-logger = { tag = "1.3.0", git = "https://github.com/MyJetTools/my-logger.git" }

rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git", features = [
    "with-tokio",
] }

tokio = { version = "*", features = ["full"] }
async-trait = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
sha2 = "*"
